# Generated by Django 5.2.17 on 2026-09-09 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('short_description', models.CharField(max_length=280)),
                ('category', models.CharField(choices=[('DevOps', 'DevOps'), ('AI', 'AI'), ('Robotics', 'Robotics'), ('Full-Stack', 'Full-Stack')], max_length=20)),
                ('featured', models.BooleanField(default=False, help_text="Shown in the homepage 'Selected work' section.")),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('in-progress', 'In progress'), ('maintained', 'Maintained')], default='completed', max_length=20)),
                ('year', models.CharField(help_text='e.g. 2025 or 2024–2025', max_length=9)),
                ('role', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('github_url', models.URLField(blank=True)),
                ('live_url', models.URLField(blank=True)),
                ('docs_url', models.URLField(blank=True)),
                ('overview', models.TextField(blank=True)),
                ('problem', models.TextField(blank=True)),
                ('contribution', models.TextField(blank=True)),
                ('stack', models.TextField(blank=True)),
                ('architecture', models.TextField(blank=True)),
                ('results', models.TextField(blank=True)),
                ('learned', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['order', '-year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('category', models.CharField(choices=[('language', 'Programming language'), ('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps & Infrastructure'), ('ai', 'AI & Robotics'), ('tool', 'Tool')], default='tool', max_length=20)),
            ],
            options={
                'verbose_name_plural': 'technologies',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CaseStudyPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('decision', 'Technical decision'), ('challenge', 'Challenge & solution')], max_length=12)),
                ('heading', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points', to='projects.project')),
            ],
            options={
                'ordering': ['kind', 'order'],
            },
        ),
        migrations.CreateModel(
            name='ProjectTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.technology')),
            ],
            options={
                'verbose_name': 'technology',
                'verbose_name_plural': 'technologies',
                'ordering': ['order', 'technology__name'],
                'unique_together': {('project', 'technology')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='projects', through='projects.ProjectTechnology', to='projects.technology'),
        ),
    ]
