# Generated by Django 5.2.17 on 2026-09-11 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('code', models.CharField(blank=True, help_text='Project code, e.g. G-CPE-110.', max_length=40)),
                ('module', models.CharField(blank=True, help_text='Curriculum module, e.g. Elementary Programming in C.', max_length=160)),
                ('pitch', models.CharField(max_length=280)),
                ('github_url', models.URLField(blank=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.')),
                ('technologies', models.ManyToManyField(blank=True, related_name='school_projects', to='projects.technology')),
            ],
            options={
                'ordering': ['order', 'code', 'title'],
            },
        ),
    ]
