# Generated by Django 5.2.17 on 2026-09-11 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_schoolproject'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolproject',
            name='details',
            field=models.TextField(blank=True, help_text="Longer write-up shown when a visitor clicks 'Read more'."),
        ),
    ]
