# Generated by Django 5.2.17 on 2026-09-13 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_schoolproject_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='pdf',
            field=models.FileField(blank=True, help_text='Optional — a report, slide deck or write-up to attach.', null=True, upload_to='projects/pdfs/'),
        ),
    ]
