# Generated by Django 5.2.17 on 2026-09-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Web Development', 'Web Development'), ('DevOps & Infrastructure', 'DevOps & Infrastructure'), ('AI & Robotics', 'AI & Robotics'), ('Tools', 'Tools')], max_length=40)),
                ('level', models.CharField(blank=True, choices=[('learning', 'Learning'), ('comfortable', 'Comfortable'), ('strong', 'Strong')], max_length=12)),
                ('icon', models.CharField(blank=True, help_text='Optional icon name / slug.', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
